#!/usr/bin/env bash
set -euo pipefail

DEST_FILE=${1:-.env}

echo "Writing env file to ${DEST_FILE}"
{
  echo "# Generated by CI/CD or local script. Do not commit real secrets."
  [ -n "${OPENROUTER_API_KEY:-}" ] && echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
  [ -n "${OPENAI_API_KEY:-}" ] && echo "OPENAI_API_KEY=${OPENAI_API_KEY}"
  [ -n "${TAVILY_API_KEY:-}" ] && echo "TAVILY_API_KEY=${TAVILY_API_KEY}"
  [ -n "${MODEL_NAME:-}" ] && echo "MODEL_NAME=${MODEL_NAME}" || echo "MODEL_NAME=gpt-4o-mini"
  [ -n "${TEMPERATURE:-}" ] && echo "TEMPERATURE=${TEMPERATURE}" || echo "TEMPERATURE=0.2"
  [ -n "${GOOGLE_SERVICE_ACCOUNT_JSON:-}" ] && echo "GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}"
  [ -n "${GSPREAD_SHEET_ID:-}" ] && echo "GSPREAD_SHEET_ID=${GSPREAD_SHEET_ID}"
  [ -n "${GSPREAD_WORKSHEET:-}" ] && echo "GSPREAD_WORKSHEET=${GSPREAD_WORKSHEET}" || echo "GSPREAD_WORKSHEET=history"
} >"${DEST_FILE}"

echo "Wrote $(wc -l <"${DEST_FILE}") lines to ${DEST_FILE}"
