name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run flake8
      run: flake8 research_agent

    - name: Run black (check)
      run: black --check research_agent

    - name: Run tests
      run: pytest -v --maxfail=1 --disable-warnings

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install minimal deps to read version
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Read version
      id: get_version
      run: |
        echo "version=$(python -c 'import research_agent; print(research_agent.__version__)')" >> $GITHUB_OUTPUT

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        IMAGE_BASE=ghcr.io/harshhajela/research-agent
        VERSION=${{ steps.get_version.outputs.version }}
        docker build -t ${IMAGE_BASE}:${VERSION} -t ${IMAGE_BASE}:latest .

    - name: Push Docker images
      run: |
        IMAGE_BASE=ghcr.io/harshhajela/research-agent
        VERSION=${{ steps.get_version.outputs.version }}
        docker push ${IMAGE_BASE}:${VERSION}
        docker push ${IMAGE_BASE}:latest
